class ContinentDefinitionService:
    # see https://dev.maxmind.com/geoip/legacy/codes/iso3166/
    @staticmethod
    def get_continent_definition(country_code):
        country_code = country_code.upper()
        print(country_code)
        if country_code == 'US' \
                or country_code == 'AR' \
                or country_code == 'MX' \
                or country_code == 'CA' \
                or country_code == 'AI' \
                or country_code == 'AG' \
                or country_code == 'AW' \
                or country_code == 'BS' \
                or country_code == 'BB' \
                or country_code == 'BZ' \
                or country_code == 'BM' \
                or country_code == 'BQ' \
                or country_code == 'VG' \
                or country_code == 'KY' \
                or country_code == 'CR' \
                or country_code == 'CU' \
                or country_code == 'CW' \
                or country_code == 'DM' \
                or country_code == 'DO' \
                or country_code == 'SV' \
                or country_code == 'GL' \
                or country_code == 'GD' \
                or country_code == 'GP' \
                or country_code == 'GT' \
                or country_code == 'HT' \
                or country_code == 'HN' \
                or country_code == 'JM' \
                or country_code == 'MQ' \
                or country_code == 'PM' \
                or country_code == 'MS' \
                or country_code == 'CW' \
                or country_code == 'KN' \
                or country_code == 'NI' \
                or country_code == 'PA' \
                or country_code == 'PR' \
                or country_code == 'BQ' \
                or country_code == 'SX' \
                or country_code == 'KN' \
                or country_code == 'LC' \
                or country_code == 'PM' \
                or country_code == 'VC' \
                or country_code == 'TT' \
                or country_code == 'TC' \
                or country_code == 'VI' \
                or country_code == 'BO' \
                or country_code == 'BR' \
                or country_code == 'CL' \
                or country_code == 'CO' \
                or country_code == 'EC' \
                or country_code == 'FK' \
                or country_code == 'GF' \
                or country_code == 'GY' \
                or country_code == 'GY' \
                or country_code == 'PY' \
                or country_code == 'PE' \
                or country_code == 'SR' \
                or country_code == 'UY' \
                or country_code == 'VE':
            return 'America'
        elif country_code == 'AP' \
                or country_code == 'AF' \
                or country_code == 'AZ' \
                or country_code == 'BH' \
                or country_code == 'BD' \
                or country_code == 'BT' \
                or country_code == 'BN' \
                or country_code == 'KH' \
                or country_code == 'CN' \
                or country_code == 'CX' \
                or country_code == 'CC' \
                or country_code == 'IO' \
                or country_code == 'GE' \
                or country_code == 'HK' \
                or country_code == 'IN' \
                or country_code == 'ID' \
                or country_code == 'IR' \
                or country_code == 'IQ' \
                or country_code == 'IL' \
                or country_code == 'JP' \
                or country_code == 'JO' \
                or country_code == 'KZ' \
                or country_code == 'KW' \
                or country_code == 'KG' \
                or country_code == 'LA' \
                or country_code == 'LB' \
                or country_code == 'MO' \
                or country_code == 'MY' \
                or country_code == 'MV' \
                or country_code == 'MN' \
                or country_code == 'MM' \
                or country_code == 'NP' \
                or country_code == 'KP' \
                or country_code == 'OM' \
                or country_code == 'PK' \
                or country_code == 'PS' \
                or country_code == 'PH' \
                or country_code == 'QA' \
                or country_code == 'SA' \
                or country_code == 'SG' \
                or country_code == 'KR' \
                or country_code == 'LK' \
                or country_code == 'SY' \
                or country_code == 'TW' \
                or country_code == 'TJ' \
                or country_code == 'TH' \
                or country_code == 'TR' \
                or country_code == 'TM' \
                or country_code == 'UZ' \
                or country_code == 'VN' \
                or country_code == 'YE':
            return 'Asia'
        elif country_code == 'AU':
            return 'Australia'
        elif country_code == 'CF' \
                or country_code == 'DZ' \
                or country_code == 'AO' \
                or country_code == 'BJ' \
                or country_code == 'BW' \
                or country_code == 'BF' \
                or country_code == 'BI' \
                or country_code == 'CV' \
                or country_code == 'CM' \
                or country_code == 'KM' \
                or country_code == 'CD' \
                or country_code == 'CG' \
                or country_code == 'CI' \
                or country_code == 'EG' \
                or country_code == 'GQ' \
                or country_code == 'ET' \
                or country_code == 'GA' \
                or country_code == 'GM' \
                or country_code == 'GH' \
                or country_code == 'GN' \
                or country_code == 'GW' \
                or country_code == 'KE' \
                or country_code == 'LS' \
                or country_code == 'LR' \
                or country_code == 'LY' \
                or country_code == 'MG' \
                or country_code == 'MW' \
                or country_code == 'ML' \
                or country_code == 'MR' \
                or country_code == 'MU' \
                or country_code == 'MA' \
                or country_code == 'MZ' \
                or country_code == 'NA' \
                or country_code == 'NE' \
                or country_code == 'NG' \
                or country_code == 'RW' \
                or country_code == 'ST' \
                or country_code == 'SN' \
                or country_code == 'SC' \
                or country_code == 'SL' \
                or country_code == 'SO' \
                or country_code == 'SS' \
                or country_code == 'SD' \
                or country_code == 'SZ' \
                or country_code == 'TZ' \
                or country_code == 'TG' \
                or country_code == 'TN' \
                or country_code == 'UG' \
                or country_code == 'ZM' \
                or country_code == 'ZW' \
                or country_code == 'ZA':
            return 'Africa'
        elif country_code == 'EU' \
                or country_code == 'AL' \
                or country_code == 'AD' \
                or country_code == 'AT' \
                or country_code == 'BY' \
                or country_code == 'BE' \
                or country_code == 'BA' \
                or country_code == 'BG' \
                or country_code == 'HR' \
                or country_code == 'CY' \
                or country_code == 'CZ' \
                or country_code == 'DK' \
                or country_code == 'EE' \
                or country_code == 'FO' \
                or country_code == 'FI' \
                or country_code == 'FR' \
                or country_code == 'DE' \
                or country_code == 'GI' \
                or country_code == 'GR' \
                or country_code == 'HU' \
                or country_code == 'IS' \
                or country_code == 'IE' \
                or country_code == 'IM' \
                or country_code == 'IT' \
                or country_code == 'RS' \
                or country_code == 'LV' \
                or country_code == 'LI' \
                or country_code == 'LT' \
                or country_code == 'LU' \
                or country_code == 'MK' \
                or country_code == 'MT' \
                or country_code == 'MD' \
                or country_code == 'MC' \
                or country_code == 'ME' \
                or country_code == 'NL' \
                or country_code == 'NO' \
                or country_code == 'PL' \
                or country_code == 'PT' \
                or country_code == 'RO' \
                or country_code == 'RU' \
                or country_code == 'SM' \
                or country_code == 'RS' \
                or country_code == 'SK' \
                or country_code == 'SI' \
                or country_code == 'ES' \
                or country_code == 'SE' \
                or country_code == 'CH' \
                or country_code == 'UA' \
                or country_code == 'GB' \
                or country_code == 'VA' \
                or country_code == 'RS':
            return 'Europe'
        else:
            return 'Others'
